In [17]:
import numpy as np
from numpy import random
from scipy import stats

### One-sample T-test

In [2]:
from scipy.stats import ttest_1samp

In [5]:
ages = [10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]
len(ages)

32

In [6]:
age_mean = np.mean(ages)
print(age_mean)

30.34375


In [11]:
sample_size = 10
sample = random.choice(ages, sample_size) #random.choice(arr, size)
print(sample)

[24 24 14 65 20 25 10 25 21 70]


In [13]:
ttest, p_val = ttest_1samp(sample, 30)  #ttest_1samp(sample, expected_val)
print(p_val)

0.9760655792644541


In [14]:
#H0 - no difference between sample and population mean
#H1 - difference between sample and poplulation mean
if p_val<0.05:
    print('reject null hypothesis')
else:
    print('accept null hypothesis')

accept null hypothesis


### Independent samples T-Test

In [19]:
random.seed(12)
classA = stats.poisson.rvs(loc=18, mu=30, size=60)
classB = stats.poisson.rvs(loc=18, mu=33, size=60)
print('classA mean:',classA.mean())
print('classB mean:', classB.mean())

classA mean: 47.75
classB mean: 50.11666666666667


In [20]:
_, p_val = stats.ttest_ind(a=classA, b=classB, equal_var=False)
print(p_val)

0.016441361202033832


In [21]:
#H0 - population means are same
#H1 - populations are different
if p_val<0.05:
    print('reject null hypothesis')
else:
    print('accept null hypothesis')

reject null hypothesis


### Paired two-sample T-test

In [23]:
math1 = np.array([4, 4, 7, 16, 20, 11, 13, 9, 11, 15])
math2 = np.array([15, 16, 14, 14, 22, 22, 23, 18, 18, 19])

In [24]:
_,p_val = stats.ttest_rel(a=math1, b=math2)
print(p_val)

0.0007875235561560145


In [25]:
if p_val<0.05:
    print('reject null hypothesis')
else:
    print('accept null hypothesis')

reject null hypothesis


### Chi-square Test

In [27]:
import pandas as pd
import seaborn as sns

In [29]:
df = sns.load_dataset('tips')
df.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [30]:
df_table = pd.crosstab(df['sex'],df['smoker'])
print(df_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [35]:
observed_vals = df_table.values
print('Observed:\n', observed_vals)

Observed:
 [[60 97]
 [33 54]]


In [39]:
val = stats.chi2_contingency(df_table)
print(val) #returns test-statistic, p-val, dof, expected vals

Chi2ContingencyResult(statistic=np.float64(0.0), pvalue=np.float64(1.0), dof=1, expected_freq=array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]]))


In [38]:
expected_vals = val[3]
expected_vals

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [45]:
r = len(df_table.iloc[0:2, 0])
c = len(df_table.iloc[0, 0:2])
ddof = (r-1)*(c-1)
print('Degree of freedom:',ddof)
alpha = 0.05

Degree of freedom: 1


In [44]:
from scipy.stats import chi2
chi_sq = sum([(o-e)**2/e for o,e in zip(observed_vals, expected_vals)])
chi_sq_stat = chi_sq[0]+chi_sq[1]
print('Chi-Square Statistic:',chi_sq_stat)

Chi-Square Statistic: 0.001934818536627623


In [46]:
critical_val = chi2.ppf(q=1-alpha, df=ddof)
print('Critical value:',critical_val)

Critical value: 3.841458820694124


In [47]:
if chi_sq_stat >= critical_val:
    print('Reject H0, there is relationship between the categorical variables')
else:
    print('Fail to reject H0, no significant relationship')

Fail to reject H0, no significant relationship


### One-Way ANOVA 

In [50]:
from scipy.stats import f_oneway

In [51]:
p1 = [89, 89, 88, 78, 79]
p2 = [93, 92, 94, 89, 88]
p3 = [89, 88, 89, 93, 90]
p4 = [81, 78, 81, 92, 82]

In [52]:
f_stat, p_value = f_oneway(p1, p2, p3, p4)
print(f'F-statistic value:{f_stat}')
print(f'p-value:{p_value}')

F-statistic value:4.625000000000002
p-value:0.016336459839780215


In [53]:
if p_value<0.05:
    print('Reject the null hypothesis')
else:
    print('Fail to reject null hypothesis')

Reject the null hypothesis


### One-sample Z-Test

In [54]:
from statsmodels.stats.weightstats import ztest

In [55]:
data = [11.8]*100
pop_mean = 12
pop_sd = 0.5

z_stat, p_val = ztest(data, value=pop_mean)
print(f'Z-statistic:{z_stat}')
print(f'p-value:{p_val}')

Z-statistic:-560128131373970.25
p-value:0.0


In [57]:
alpha = 0.05
if p_val<alpha:
    print('reject null hypothesis, avg battey life different from claimed')
else:
    print('fail to reject null hypothesis, avg battery life equal to claimed')

reject null hypothesis, avg battey life different from claimed


### F-Test

In [60]:
grp1 = np.random.rand(25)
grp2 = np.random.rand(20)

var1 = np.var(grp1, ddof=1)
var2 = np.var(grp2, ddof=1)

f_val = var1/var2

df1 = len(grp1)-1
df2 = len(grp2)-1

p_val = 2*min(stats.f.cdf(f_val, df1, df2), 1 - stats.f.cdf(f_val, df1, df2))

print('dof 1:', df1)
print('dof 2:',df2)
print('F-statistic:', f_val)
print('p-value:',p_val)

dof 1: 24
dof 2: 19
F-statistic: 0.9305117672642171
p-value: 0.8563151466855379


In [61]:
alpha = 0.05
if p_val<alpha:
    print('reject null hypothesis, variances are different')
else:
    print('fail to reject null hypothesis, no significant difference')

fail to reject null hypothesis, no significant difference
